Prevent overwrite, handle spaces in vault paths, cleanup output

diff --git a/apvault b/apvault
--- a/apvault
+++ b/apvault
@@ -83,8 +83,8 @@ case $subcommand in
     *)
         sub_"${subcommand}" "$@"
         if [ $? = 127 ]; then
-            echo "Error: '$subcommand' is not a known subcommand." >&2
-            echo "       Run 'apvault.sh --help' for a list of known subcommands." >&2
+            echo "Error: APVault: '$subcommand' is not a known subcommand." >&2
+            echo "       Run 'apvault --help' for a list of known subcommands." >&2
             exit 1
         fi
         ;;
